version: '3.4'

services:
  matdatadb:
    container_name: matdatadb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=SibmDb
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mat.gov.ao
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  matdata.api:
    container_name: matdata.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Host=matdatadb;Port=5432;Database=SibmDb;Username=admin;Password=admin1234;"
    depends_on:
      - matdatadb
    ports:
        - "5000:80"
