using MatData.Models.Records;
using MatData.ViewModels;
using System;

namespace MatData.Serialization
{
    public static class Q83Mapper
    {
        public static Q83Model Serialize(Q83Record model)
        {
            return new Q83Model
            {
               NomeOperadorIndustrial = model.q8306,
               DataFundacao = model.q8307,
               EstadoFuncional = model.q8308,
               Nacionalidade = model.q8309,
               FormaJuridica = model.q8310,
               TipoIndustriaTransformadora = model.q8311,
               TipoIndustriaAcordoDimensao = model.q8312,
               EnquadramentoPoloDesenvol = model.q8313,
               IdPolo = model.q8313 == "Sim" ? model.q8314 : null,
               LocalUnFabril = model.q8315,
               FotoFrontal = model.q8316,
               FotoInterior = model.q8317,
               FotoProducao = model.q8318,
               EntidadeAlvaraIndustrial = model.q8319,
               NumAlvara = model.q8319 == "Sim" ? model.q8320 : null,
               EntidadeCertificAmbient = model.q8321,
               NumCertificacao = model.q8321 == "Sim" ? model.q8322 : null,
               IdServico = model.q8323,
               Contacto = model.q8324,
               Email = model.q8325,
               Website = model.q8326,
               IdPrincipaisProdProduzidos = model.q8327,
               //Acesso a Sistemas de Apoio à actividade industrial = model.q830,
               SisApoioBeneficiou = model.q8328,
               IdEntidadesApoio = model.q8329,
               ValCredSectorAnoCorr = double.Parse(model.q8330),
               ValCredSectorUltimos5Anos = double.Parse(model.q8331),
               //Movimento Associativo = model.q830,
               PertenceAssociacao = model.q8332,
               IdAssociacao = model.q8332 == "Sim" ? model.q8333 : null,
               PrincipBeneficios = model.q8332 == "Sim" ? model.q8334 : null,
               //Produto de maior produção(PMP) = model.q830,
               IdProdutoPMP = model.q8335,
               QtdProdProduzidoAnoTransPMP = model.q8336,
               QtdProdProduzidoTrimestralmentePMP = model.q8337,
               CustoProducaoUnMedidaPMP = double.Parse(model.q8338),
               ValVendaProdutoProduzidoUnPMP = double.Parse(model.q8339),
               PrecoComercializacaoUnPMP = double.Parse(model.q8340),
               //Produto de segunda maior produção(PSMP) = model.q830,
               IdProdutoPSMP = model.q8341,
               QtdProdProduzidoAnoTransPSMP = model.q8342,
               QtdProdProduzidoTrimestralmentePSMP = model.q8343,
               CustoProducaoUnMedidaPSMP = double.Parse(model.q8344),
               ValVendaProdutoProduzidoUnPSMP = double.Parse(model.q8345),
               PrecoComercializacaoUnPSMP = double.Parse(model.q8346),
               //Produto de terceira maior produção(PTMP) = model.q830,
               IdProdutoPTMP = model.q8347,
               QtdProdProduzidoAnoTransPTMP = model.q8348,
               QtdProdProduzidoTrimestralmentePTMP = model.q8349,
               CustoProducaoUnMedidaPTMP = double.Parse(model.q8350),
               ValVendaProdutoProduzidoUnPTMP = double.Parse(model.q8351),
               PrecoComercializacaoUnPTMP = double.Parse(model.q8352),
               //Escoamento do produto e condições de armazenamento e transporte = model.q830,
               PrincipaisDestinosEscoamento = model.q8353,
               FormArmazenamento = model.q8354,
               CadeiaDistribuicao = model.q8355,
               //Indicadores do Negócio = model.q830,
               NumClientes = Int32.Parse(model.q8356),
               NumMensalCliente = Int32.Parse(model.q8357),
               DespesasMensais = double.Parse(model.q8358),
               ReceitasMensais = double.Parse(model.q8359),
               LucroMensal = double.Parse(model.q8360),
               ContabilidadeOrganizada = model.q8361,
               VolumeNegocios = model.q8361 =="Sim" ?  double.Parse(model.q8362) : 0,
               SituacaoTributRegularizada = model.q8361 =="Sim" ?  model.q8363 : null,
               ValorLiqImpostos = model.q8361 =="Sim" ?  double.Parse(model.q8364) : 0,
               //Força de Trabalho = model.q830,
               NumDirProd = Int32.Parse(model.q8365),
               NumEspecialistas = Int32.Parse(model.q8366),
               NumTecIntermedios = Int32.Parse(model.q8367),
               NumAdmEquiparados = Int32.Parse(model.q8368),
               NumTrabServicosProteccao = Int32.Parse(model.q8369),
               NumTrabQualificadosCulturas = Int32.Parse(model.q8370),
               NumTrabQualificadosConstrucao = Int32.Parse(model.q8371),
               NumOperVeiculos = Int32.Parse(model.q8372),
               NumTrabNaoQualificados = Int32.Parse(model.q8373),
               PrincipConstraIdentificados = model.q8375,
               Observacoes = model.q8376,
            };
        }
    }
}
